### PR TITLE
Python wheels

### PR DESCRIPTION
**Pull request by berndgassmann**
* Updated map to 2.5.0
* Added python wheels build
* Removed static linking on general python build and remove the
additional not required module shared library
* Remove outdated and complicated plain cmake handling from docu
* Updated version number to 4.5.0

#### Description

Fixes #  

#### Where has this been tested?

  * **Platform(s):** ...
  * **Library version:** ...

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/113)

### CODE REVIEW

**Comment by berndgassmann** [comment]
We have to wait until the latest carla-map changes are merged and the submodule was updated to the correct commit-id

**Review by fabianoboril — APPROVED** [review]
> Reviewed 29 of 29 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @berndgassmann)

**Review by fabianoboril — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/113)* status: all files reviewed, 1 unresolved discussion (waiting on @berndgassmann)

___
*[doc/CHANGELOG.md, line 12 at r2](https://reviewable.io/reviews/intel/ad-rss-lib/113#-MiuLtHr1l1TOYVqALie:-MiuLtHr1l1TOYVqALif:b-63een4) ([raw file](https://github.com/intel/ad-rss-lib/blob/c773983574a5156f370f5c9a039780b4af8e611c/doc/CHANGELOG.md#L12)):*
> ```Markdown
> #### :ghost: Maintenance
> * Ease version number handling and folder layout
> * Update map to latest v2.4.5_hotfix commit
> ```

Shouldn't we update to the commit, that is currently in review?

**Review by berndgassmann — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/113)* status: all files reviewed, 1 unresolved discussion (waiting on @fabianoboril)

___
*[doc/CHANGELOG.md, line 12 at r2](https://reviewable.io/reviews/intel/ad-rss-lib/113#-MiuLtHr1l1TOYVqALie:-MiucYnQ-nKLLSjgQ2B0:bhj8stp) ([raw file](https://github.com/intel/ad-rss-lib/blob/c773983574a5156f370f5c9a039780b4af8e611c/doc/CHANGELOG.md#L12)):*
<details><summary><i>Previously, fabianoboril (Fabian Oboril) wrote…</i></summary><blockquote>

Shouldn't we update to the commit, that is currently in review?
</blockquote></details>

I've created a separate PR for the 4.4.2 changelog update, so let's first merge that one. Then update this one later.

**Review by fabianoboril — APPROVED** [review]

**Pull request merged**
