### PR TITLE
Improve python user interface

### PR DESCRIPTION
**Pull request by berndgassmann**
Build documentation update to make the plain cmake build more robust and especially make repeated builds with -DBUILD_PYTHON_BINDING=ON working
Improved user interface of python binding
Prepared generated files for next release

#### Description

Fixes #  

#### Where has this been tested?

  * **Platform(s):** ...
  * **Library version:** ...

#### Possible Drawbacks

---
This change is [Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/81)

### CODE REVIEW

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/81)* status: all files reviewed, 3 unresolved discussions (waiting on @fabianoboril)

___
*[ad_rss_map_integration/impl/tests/RssSceneCreationTest.hpp, line 179 at r1](https://reviewable.io/reviews/intel/ad-rss-lib/81#-MFWEWc69XAlbHNGF1mB:-MFWEWc72vhd7HGtnb4f:bpxs2li) ([raw file](https://github.com/intel/ad-rss-lib/blob/c88d4e69d54f0d8b51b1895bd2230fab639cef63/ad_rss_map_integration/impl/tests/RssSceneCreationTest.hpp#L179)):*
> ```cpp
>     ::ad::map::match::AdMapMatching mapMatching;
>     object.mapMatchedBoundingBox
>       = mapMatching.getMapMatchedBoundingBox(object.enuPosition, ::ad::physics::Distance(2.0));
> ```

speeds up the unit tests to 8 seconds in sum.
___
*[ad_rss_map_integration/python/generate_python_lib.py.in, line 49 at r1](https://reviewable.io/reviews/intel/ad-rss-lib/81#-MFWEg8N12_H9DQ8AGUI:-MFWEg8N12_H9DQ8AGUJ:bo0mib9) ([raw file](https://github.com/intel/ad-rss-lib/blob/ffa69395dcce65dc16b8a3eb808541e04e3b22bc/ad_rss_map_integration/python/generate_python_lib.py.in#L49)):*
> ```
>                             )
> 
>     additional_replacements = {
> ```

these are now filtered by the generic namespace filtering
___
*[dependencies/map, line 1 at r1](https://reviewable.io/reviews/intel/ad-rss-lib/81#-MFWEy0I5OUgiiDAnnQX:-MFWEy0I5OUgiiDAnnQY:b-gawuw4) ([raw file](https://github.com/intel/ad-rss-lib/blob/c88d4e69d54f0d8b51b1895bd2230fab639cef63/dependencies/map#L1)):*
> ```
> Subproject commit 04b6e96c058e57f2bc7581b48f441b1e723afd91
> ```

we have to wait with merging until ad-map has a new commit id after squash

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/81)* status: all files reviewed, 3 unresolved discussions (waiting on @fabianoboril)

**Review by berndgassmann — COMMENTED** [review]
> Reviewed 30 of 35 files at r3, 135 of 135 files at r5.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/81)* status: all files reviewed, 2 unresolved discussions (waiting on @fabianoboril)

**Review by fabianoboril — APPROVED** [review]
> Reviewed 1 of 35 files at r3.
> *[Reviewable](https://reviewable.io/reviews/intel/ad-rss-lib/81)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
